In [7]:
import os
import matplotlib as mp
import pandas as pd
import plotly as pt

In [8]:
Faceset = os.path.join('posts_and_comments.csv')
fb_df = pd.read_csv (Faceset)

In [9]:
fb_df.head()

,reactions/timestamp,reactions/data/0/reaction/reaction,reactions/data/0/reaction/actor,reactions/title,reactions/attachments/0/data/0/media/uri
0,1614031972,LIKE,Bruna GonÃ§alves,Bruna GonÃ§alves curtiu a foto de Ignacio Guevel.,NaN
1,1612446315,LIKE,Bruna GonÃ§alves,Bruna GonÃ§alves curtiu uma publicaÃ§Ã£o de Ma...,NaN
2,1611973471,LIKE,Bruna GonÃ§alves,Bruna GonÃ§alves curtiu a foto de Noticias No ...,NaN
3,1611973469,LIKE,Bruna GonÃ§alves,Bruna GonÃ§alves curtiu o comentÃ¡rio de Orlan...,NaN
4,1611935102,LIKE,Bruna GonÃ§alves,Bruna GonÃ§alves curtiu a foto de Time Do Povo.,NaN

In [10]:
#Filter
tm = fb_df['reactions/timestamp']

In [11]:
#Create columns Year, Month, Day, Hour

fb_df['datetime']= pd.to_datetime(tm, unit ='s', yearfirst= True )

fb_df['year']= fb_df['datetime'].dt.year
fb_df['month']= fb_df['datetime'].dt.month
fb_df['day']= fb_df['datetime'].dt.day
fb_df['hour']= fb_df['datetime'].dt.hour

In [12]:
fb_df.head()

,reactions/timestamp,reactions/data/0/reaction/reaction,reactions/data/0/reaction/actor,reactions/title,reactions/attachments/0/data/0/media/uri,datetime,year,month,day,hour
0,1614031972,LIKE,Bruna GonÃ§alves,Bruna GonÃ§alves curtiu a foto de Ignacio Guevel.,NaN,2021-02-22 22:12:52,2021,2,22,22
1,1612446315,LIKE,Bruna GonÃ§alves,Bruna GonÃ§alves curtiu uma publicaÃ§Ã£o de Ma...,NaN,2021-02-04 13:45:15,2021,2,4,13
2,1611973471,LIKE,Bruna GonÃ§alves,Bruna GonÃ§alves curtiu a foto de Noticias No ...,NaN,2021-01-30 02:24:31,2021,1,30,2
3,1611973469,LIKE,Bruna GonÃ§alves,Bruna GonÃ§alves curtiu o comentÃ¡rio de Orlan...,NaN,2021-01-30 02:24:29,2021,1,30,2
4,1611935102,LIKE,Bruna GonÃ§alves,Bruna GonÃ§alves curtiu a foto de Time Do Povo.,NaN,2021-01-29 15:45:02,2021,1,29,15

In [13]:
#Clean our Data Frame

fb_df.columns = ['Timestamp', 'Reaction','Actor','Title','Uri','Datetime','Year','Month','Day','Hour']
new_df = fb_df.set_index(fb_df['Actor'])
fb_df = new_df.drop(columns=['Timestamp', 'Actor','Uri'])

In [14]:
fb_df.head()

,Reaction,Title,Datetime,Year,Month,Day,Hour
Actor,,,,,,,
Bruna GonÃ§alves,LIKE,Bruna GonÃ§alves curtiu a foto de Ignacio Guevel.,2021-02-22 22:12:52,2021,2,22,22
Bruna GonÃ§alves,LIKE,Bruna GonÃ§alves curtiu uma publicaÃ§Ã£o de Ma...,2021-02-04 13:45:15,2021,2,4,13
Bruna GonÃ§alves,LIKE,Bruna GonÃ§alves curtiu a foto de Noticias No ...,2021-01-30 02:24:31,2021,1,30,2
Bruna GonÃ§alves,LIKE,Bruna GonÃ§alves curtiu o comentÃ¡rio de Orlan...,2021-01-30 02:24:29,2021,1,30,2
Bruna GonÃ§alves,LIKE,Bruna GonÃ§alves curtiu a foto de Time Do Povo.,2021-01-29 15:45:02,2021,1,29,15